# my-smart-contract-project/docker-compose.yml


services:
  golem-node:
    build:
      context: ./golem-workers/golem-node
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      YAGNA_AUTOCONF_APPKEY: ${YAGNA_AUTOCONF_APPKEY}
      YAGNA_API_URL: ${YAGNA_API_URL}
      GSB_URL: ${GSB_URL}
    volumes:
      - yagna-data:/root/.local/share/yagna
    ports:
      - "7465:7465"
    networks:
      - my-network

  web:
    build:
      context: ./golem-workers/web
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      YAGNA_APPKEY: ${YAGNA_APPKEY}
      YAGNA_API_URL: http://golem-node:7465
      #GSB_URL: tcp://golem-node:7464
      GLOBAL_CONTEXTS: '["golem_reputation.ReputationService"]'
    ports:
      - "8000:8000"
    depends_on:
      - golem-node
    networks:
      - my-network

  node-server:
    build:
      context: ./node-server
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      PRIVATE_KEY: ${PRIVATE_KEY}
      ALCHEMY_API_URL: ${ALCHEMY_API_URL}
      API_KEY: ${API_KEY}
      WEB_URL: http://web:8000/deploy
    ports:
      - "3000:3000"
    depends_on:
      - golem-node
      - web
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  yagna-data:
